# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-19 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour1', models.CharField(max_length=30)),
                ('hour2', models.CharField(max_length=30)),
                ('hour3', models.CharField(max_length=30)),
                ('hour4', models.CharField(max_length=30)),
                ('hour5', models.CharField(max_length=30)),
                ('hour6', models.CharField(max_length=30)),
                ('hour7', models.CharField(max_length=30)),
                ('hour8', models.CharField(max_length=30)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.Day')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='duration',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='invigilation',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 3, 19, 16, 11, 25, 26258, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invigilation',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 3, 19, 16, 11, 30, 532736, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='blankomr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='malpractice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='set_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examination',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.Months'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.ExaminationType'),
        ),
        migrations.AlterUniqueTogether(
            name='arrangement',
            unique_together=set([('examination', 'date', 'subject')]),
        ),
    ]
