# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-19 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0002_auto_20170319_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arrangement',
            unique_together=set([]),
        ),
    ]
