# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-19 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0003_auto_20170319_1628'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arrangement',
            unique_together=set([('id', 'examination', 'date', 'subject')]),
        ),
    ]
