# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-20 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0004_auto_20170319_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='max_set',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='set_number',
            field=models.IntegerField(default=0),
        ),
    ]
