# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0005_auto_20170320_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
